MTL: MyRunnable Class Reference
MyRunnable Class Reference
Public Member Functions
MyRunnable ()=default
virtual ~MyRunnable ()=default
void run (MTL::MTLThreadInterface *threadIf)
Run the runnable.
void stop ()
Stop the runnable.
void suspend ()
Suspend the runnable.
void resume ()
Resume the runnable.
void clean_exit ()
A clean Exit of the runnable.
void force_exit ()
Force the runnable to exit.
MyRunnable (MTL::MTLSharedMemory *sharedMemory)
virtual ~MyRunnable ()=default
void run (MTL::MTLThreadInterface *threadIf)
Run the runnable.
void stop ()
Stop the runnable.
void suspend ()
Suspend the runnable.
void resume ()
Resume the runnable.
void clean_exit ()
A clean Exit of the runnable.
void force_exit ()
Force the runnable to exit.
Private Attributes
MTL::MTLSharedMemory * m_sharedMemory
Constructor & Destructor Documentation
MyRunnable() [1/2]
MyRunnable::MyRunnable () default
~MyRunnable() [1/2]
virtual MyRunnable::~MyRunnable () virtual default
MyRunnable() [2/2]
MyRunnable::MyRunnable (MTL::MTLSharedMemory * sharedMemory) inline
References m_sharedMemory.
Referenced by main().
~MyRunnable() [2/2]
virtual MyRunnable::~MyRunnable () virtual default
Member Function Documentation
clean_exit() [1/2]
void MyRunnable::clean_exit () inline virtual
A clean Exit of the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
clean_exit() [2/2]
void MyRunnable::clean_exit () inline virtual
A clean Exit of the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
force_exit() [1/2]
void MyRunnable::force_exit () inline virtual
Force the runnable to exit.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
force_exit() [2/2]
void MyRunnable::force_exit () inline virtual
Force the runnable to exit.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
resume() [1/2]
void MyRunnable::resume () inline virtual
Resume the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
resume() [2/2]
void MyRunnable::resume () inline virtual
Resume the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
run() [1/2]
void MyRunnable::run (MTL::MTLThreadInterface * threadIf) inline virtual
Run the runnable.
Parameters
threadIf The thread interface.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::EXITED, MTL::MTLThreadInterface::getThreadState(), MTL::RUNNING, MTL::MTLThreadInterface::setThreadState(), MTL::STOPPED, and MTL::SUSPENDED.
run() [2/2]
void MyRunnable::run (MTL::MTLThreadInterface * threadIf) inline virtual
Run the runnable.
Parameters
threadIf The thread interface.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::EXITED, MTL::MTLSharedMemory::getSharedObjectById(), MTL::MTLThreadInterface::getThreadState(), MySharedObject::getValue(), m_sharedMemory, MTL::MTLSharedMemory::releaseSharedObject(), MTL::RUNNING, MySharedObject::setValue(), MTL::STOPPED, and MTL::SUSPENDED.
stop() [1/2]
void MyRunnable::stop () inline virtual
Stop the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
stop() [2/2]
void MyRunnable::stop () inline virtual
Stop the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
suspend() [1/2]
void MyRunnable::suspend () inline virtual
Suspend the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
suspend() [2/2]
void MyRunnable::suspend () inline virtual
Suspend the runnable.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
Field Documentation
m_sharedMemory
MTL::MTLSharedMemory* MyRunnable::m_sharedMemory private
Referenced by MyRunnable(), and run().
The documentation for this class was generated from the following file:
example/example_1/main.cpp