MTL: MTL::MTLSharedObject Class Reference
MTL::MTLSharedObject Class Reference
Class that implements a shared object.
#include <MTLSharedObject.h>
Public Member Functions
MTLSharedObject (SharedObjectId id)
Construct a new MTLSharedObject object.
virtual ~MTLSharedObject ()
Destroy the MTLSharedObject object.
SharedObjectId getObjId ()
Get the id of the object.
MTLSharedObject & getObj ()
Lock the object and Get the object reference.
void releaseObj ()
Release the object lock. (this function should be used only after the end of the critical section that use the object)
Private Attributes
SharedObjectId objId
std::mutex m_mutex
Detailed Description
Class that implements a shared object.
This class is a shared object that can be used to share data between threads.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLSharedObject()
MTL::MTLSharedObject::MTLSharedObject (SharedObjectId id)
Construct a new MTLSharedObject object.
Parameters
id The id of the object.
Author
@ZigRazor
Date
2020-02-16
References m_mutex, and objId.
~MTLSharedObject()
MTL::MTLSharedObject::~MTLSharedObject () virtual
Destroy the MTLSharedObject object.
Author
@ZigRazor
Date
2020-02-16
References m_mutex.
Member Function Documentation
getObj()
MTLSharedObject & MTL::MTLSharedObject::getObj ()
Lock the object and Get the object reference.
Returns
MTLSharedObject& The object.
Author
@ZigRazor
Date
2020-02-16
References m_mutex.
Referenced by MTL::MTLSharedMemory::getSharedObjectById().
getObjId()
SharedObjectId MTL::MTLSharedObject::getObjId ()
Get the id of the object.
Returns
SharedObjectId The id of the object.
Author
@ZigRazor
Date
2020-02-16
References objId.
Referenced by MTL::MTLSharedMemory::addSharedObject(), and MTL::MTLSharedMemory::releaseSharedObject().
releaseObj()
void MTL::MTLSharedObject::releaseObj ()
Release the object lock. (this function should be used only after the end of the critical section that use the object)
Author
@ZigRazor
Date
2020-02-16
References m_mutex.
Referenced by MTL::MTLSharedMemory::releaseSharedObject().
Field Documentation
m_mutex
std::mutex MTL::MTLSharedObject::m_mutex private
The mutex of the object.
Referenced by getObj(), MTLSharedObject(), releaseObj(), and ~MTLSharedObject().
objId
SharedObjectId MTL::MTLSharedObject::objId private
The id of the object.
Referenced by getObjId(), and MTLSharedObject().
The documentation for this class was generated from the following files:
include/MTLSharedObject.h
src/MTLSharedObject.cpp