MTL: MTL::MTLOrderedTask Class Reference
MTL::MTLOrderedTask Class Reference
Ordered Task.
#include <MTLOrderedTask.h>
Public Member Functions
MTLOrderedTask (const TaskName &taskname, MTLRunnableTask &runnableTask)
Constructor.
virtual ~MTLOrderedTask ()
Destructor.
virtual std::shared_ptr< void > run (MTLTaskInterface *interface=nullptr)
Run the task.
TaskName getTaskName ()
Get the Task Name.
void addPredecessor (std::shared_ptr< MTLOrderedTask > task)
Add a predecessor task.
void addSuccessor (std::shared_ptr< MTLOrderedTask > task)
Add a successor task.
std::shared_ptr< void > getPredecessorResult (const TaskName &taskName)
Get the Predecessor Result object.
const std::unordered_map< TaskName, std::shared_ptr< void > > & getPredecessorsResults ()
Get the Predecessors Results object.
bool hasSuccessor ()
Check if the task has Successors.
Public Member Functions inherited from MTL::MTLTask
MTLTask (MTLRunnableTask &runnableTask)
Construct a new MTLTask object.
virtual ~MTLTask ()
Destroy the MTLTask object.
virtual std::shared_ptr< void > getResult ()
Get the result of the task. When the execution is finished and the result is available.
virtual void waitResult ()
Wait for the result of the task.
Private Attributes
TaskName m_name
std::unordered_map< TaskName, std::shared_ptr< MTLOrderedTask > > m_predecessor
std::unordered_map< TaskName, std::shared_ptr< MTLOrderedTask > > m_successor
std::unordered_map< TaskName, std::shared_ptr< void > > m_predecessorResults
Additional Inherited Members
Protected Attributes inherited from MTL::MTLTask
MTLRunnableTask & m_runnableTask
The runnable task.
std::future< std::shared_ptr< void > > m_future
The future object.
std::mutex m_futureMutex
The mutex for the future object.
std::shared_ptr< void > m_result
The result of the task.
Detailed Description
Ordered Task.
This class is the implementation of the MTLOrderedTask.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLOrderedTask()
MTL::MTLOrderedTask::MTLOrderedTask (const TaskName & taskname, MTLRunnableTask & runnableTask)
Constructor.
Parameters
taskName The name of the task.
runnableTask The runnable task.
Author
@ZigRazor
Date
2020-02-16
References m_name, m_predecessor, m_successor, and MTL::MTLTask::MTLTask().
Referenced by MTL::MTLTaskFlow::MTLTaskFlow().
~MTLOrderedTask()
MTL::MTLOrderedTask::~MTLOrderedTask () virtual
Destructor.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
addPredecessor()
void MTL::MTLOrderedTask::addPredecessor (std::shared_ptr< MTLOrderedTask > task)
Add a predecessor task.
Parameters
task The predecessor task
Author
@ZigRazor
Date
2020-02-16
References getTaskName(), and m_predecessor.
Referenced by MTL::MTLTaskFlow::precede(), and MTL::MTLTaskFlow::succeed().
addSuccessor()
void MTL::MTLOrderedTask::addSuccessor (std::shared_ptr< MTLOrderedTask > task)
Add a successor task.
Parameters
task The successor task
Author
@ZigRazor
Date
2020-02-16
References getTaskName(), and m_successor.
Referenced by MTL::MTLTaskFlow::precede(), and MTL::MTLTaskFlow::succeed().
getPredecessorResult()
std::shared_ptr< void > MTL::MTLOrderedTask::getPredecessorResult (const TaskName & taskName) virtual
Get the Predecessor Result object.
Parameters
taskName The name of the predecessor task
Returns
std::shared_ptr<void> The result of the predecessor task
Author
@ZigRazor
Date
2022-02-16
Implements MTL::MTLOrderedTaskInterface.
References MTL::MTLTask::getResult(), and m_predecessor.
getPredecessorsResults()
const std::unordered_map< TaskName, std::shared_ptr< void > > & MTL::MTLOrderedTask::getPredecessorsResults () virtual
Get the Predecessors Results object.
Returns
const std::unordered_map<TaskName, std::shared_ptr<void>>& The predecessors results
Author
@ZigRazor
Date
2022-02-16
Implements MTL::MTLOrderedTaskInterface.
References MTL::MTLTask::getResult(), m_predecessor, and m_predecessorResults.
getTaskName()
TaskName MTL::MTLOrderedTask::getTaskName () virtual
Get the Task Name.
Returns
TaskName The Task Name
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLOrderedTaskInterface.
References m_name.
Referenced by addPredecessor(), addSuccessor(), MTL::MTLTaskFlow::precede(), and MTL::MTLTaskFlow::succeed().
hasSuccessor()
bool MTL::MTLOrderedTask::hasSuccessor ()
Check if the task has Successors.
Returns
true If the task has successors
false Otherwise
References m_successor.
Referenced by MTL::MTLTaskFlow::getResult(), and MTL::MTLTaskFlow::waitResult().
run()
std::shared_ptr< void > MTL::MTLOrderedTask::run (MTLTaskInterface * interface = nullptr) virtual
Run the task.
Parameters
interface Task Interface
Returns
std::shared_ptr<void> The result of the run
Author
@ZigRazor
Date
2020-02-16
Reimplemented from MTL::MTLTask.
Reimplemented in MTL::MTLTaskFlow.
References MTL::MTLTask::m_future, MTL::MTLTask::m_runnableTask, and MTL::MTLRunnableTask::run().
Referenced by MTL::MTLTaskFlow::run().
Field Documentation
m_name
TaskName MTL::MTLOrderedTask::m_name private
The name of the task
Referenced by getTaskName(), and MTLOrderedTask().
m_predecessor
std::unordered_map<TaskName, std::shared_ptr<MTLOrderedTask> > MTL::MTLOrderedTask::m_predecessor private
The predecessor tasks
Referenced by addPredecessor(), getPredecessorResult(), getPredecessorsResults(), and MTLOrderedTask().
m_predecessorResults
std::unordered_map<TaskName, std::shared_ptr<void> > MTL::MTLOrderedTask::m_predecessorResults private
The predecessor results
Referenced by getPredecessorsResults().
m_successor
std::unordered_map<TaskName, std::shared_ptr<MTLOrderedTask> > MTL::MTLOrderedTask::m_successor private
The successor tasks
Referenced by addSuccessor(), hasSuccessor(), and MTLOrderedTask().
The documentation for this class was generated from the following files:
include/MTLOrderedTask.h
src/MTLOrderedTask.cpp