MTL: MTL::MTLTaskFlow Class Reference
MTL::MTLTaskFlow Class Reference
Task Flow Class.
#include <MTLTaskFlow.h>
Public Member Functions
MTLTaskFlow (const TaskName &taskName="")
Construct a new MTLTaskFlow object.
virtual ~MTLTaskFlow ()
Destroy the MTLTaskFlow object.
virtual std::shared_ptr< void > run (MTLTaskInterface *interface=nullptr)
Run the Task Flow.
virtual std::shared_ptr< void > getResult ()
Get the Result object.
virtual void waitResult ()
Wait for the task to finish.
void precede (std::shared_ptr< MTLOrderedTask > taskA, std::shared_ptr< MTLOrderedTask > taskB)
Declare the taskA as a predecessor of taskB.
void succeed (std::shared_ptr< MTLOrderedTask > taskA, std::shared_ptr< MTLOrderedTask > taskB)
Declare the taskA as a successor of taskB.
Public Member Functions inherited from MTL::MTLOrderedTask
MTLOrderedTask (const TaskName &taskname, MTLRunnableTask &runnableTask)
Constructor.
virtual ~MTLOrderedTask ()
Destructor.
TaskName getTaskName ()
Get the Task Name.
void addPredecessor (std::shared_ptr< MTLOrderedTask > task)
Add a predecessor task.
void addSuccessor (std::shared_ptr< MTLOrderedTask > task)
Add a successor task.
std::shared_ptr< void > getPredecessorResult (const TaskName &taskName)
Get the Predecessor Result object.
const std::unordered_map< TaskName, std::shared_ptr< void > > & getPredecessorsResults ()
Get the Predecessors Results object.
bool hasSuccessor ()
Check if the task has Successors.
Public Member Functions inherited from MTL::MTLTask
MTLTask (MTLRunnableTask &runnableTask)
Construct a new MTLTask object.
virtual ~MTLTask ()
Destroy the MTLTask object.
Private Attributes
std::unordered_map< TaskName, std::shared_ptr< MTLOrderedTask > > m_orderedTasks
The ordered tasks.
Additional Inherited Members
Protected Attributes inherited from MTL::MTLTask
MTLRunnableTask & m_runnableTask
The runnable task.
std::future< std::shared_ptr< void > > m_future
The future object.
std::mutex m_futureMutex
The mutex for the future object.
std::shared_ptr< void > m_result
The result of the task.
Detailed Description
Task Flow Class.
This class implement MTLTaskFlow.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLTaskFlow()
MTL::MTLTaskFlow::MTLTaskFlow (const TaskName & taskName = "")
Construct a new MTLTaskFlow object.
Parameters
taskName The task name.
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLOrderedTask::MTLOrderedTask().
~MTLTaskFlow()
MTL::MTLTaskFlow::~MTLTaskFlow () virtual
Destroy the MTLTaskFlow object.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
getResult()
std::shared_ptr< void > MTL::MTLTaskFlow::getResult () virtual
Get the Result object.
Returns
std::shared_ptr<void> The result of the task execution.
Author
@ZigRazor
Date
2020-02-16
Reimplemented from MTL::MTLTask.
References MTL::MTLTask::getResult(), MTL::MTLOrderedTask::hasSuccessor(), and m_orderedTasks.
precede()
void MTL::MTLTaskFlow::precede (std::shared_ptr< MTLOrderedTask > taskA, std::shared_ptr< MTLOrderedTask > taskB)
Declare the taskA as a predecessor of taskB.
Parameters
taskA The predecessor task
taskB The successor task
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLOrderedTask::addPredecessor(), MTL::MTLOrderedTask::addSuccessor(), MTL::MTLOrderedTask::getTaskName(), and m_orderedTasks.
run()
std::shared_ptr< void > MTL::MTLTaskFlow::run (MTLTaskInterface * interface = nullptr) virtual
Run the Task Flow.
Parameters
interface The task interface.
Returns
std::shared_ptr<void> The result of the run.
Author
@ZigRazor
Date
2020-02-16
Reimplemented from MTL::MTLOrderedTask.
References m_orderedTasks, and MTL::MTLOrderedTask::run().
succeed()
void MTL::MTLTaskFlow::succeed (std::shared_ptr< MTLOrderedTask > taskA, std::shared_ptr< MTLOrderedTask > taskB)
Declare the taskA as a successor of taskB.
Parameters
taskA The successor task
taskB The predecessor task
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLOrderedTask::addPredecessor(), MTL::MTLOrderedTask::addSuccessor(), MTL::MTLOrderedTask::getTaskName(), and m_orderedTasks.
waitResult()
void MTL::MTLTaskFlow::waitResult () virtual
Wait for the task to finish.
Author
@ZigRazor
Date
2020-02-16
Reimplemented from MTL::MTLTask.
References MTL::MTLOrderedTask::hasSuccessor(), m_orderedTasks, and MTL::MTLTask::waitResult().
Field Documentation
m_orderedTasks
std::unordered_map<TaskName, std::shared_ptr<MTLOrderedTask> > MTL::MTLTaskFlow::m_orderedTasks private
The ordered tasks.
Referenced by getResult(), precede(), run(), succeed(), and waitResult().
The documentation for this class was generated from the following files:
include/MTLTaskFlow.h
src/MTLTaskFlow.cpp