MTL: MTL::MTLThreadManager Class Reference
MTL::MTLThreadManager Class Reference
Class that implements a thread manager.
#include <MTLThreadManager.h>
Public Member Functions
MTLThreadManager ()
Construct a new MTLThreadManager object.
virtual ~MTLThreadManager ()
Destroy the MTLThreadManager object.
virtual void run (MTLThreadInterface *threadIf)
Start the thread manager.
virtual void suspend ()
Suspend the thread manager.
virtual void resume ()
Resume the thread manager.
virtual void stop ()
Stop the thread manager.
virtual void clean_exit ()
A clean Exit of the thread manager.
virtual void force_exit ()
Force the thread manager to exit.
void addThread (std::unique_ptr< MTLThread > thread)
Add a thread to the thread manager.
void setSleepTime (int sleep_time)
Set the Sleep Time object.
Protected Attributes
std::vector< std::unique_ptr< MTLThread > > m_threads
std::mutex m_threads_mutex
Private Attributes
unsigned int m_sleep_time
Detailed Description
Class that implements a thread manager.
This class is a thread manager that can be used to manage threads.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLThreadManager()
MTL::MTLThreadManager::MTLThreadManager ()
Construct a new MTLThreadManager object.
Author
@ZigRazor
Date
2020-02-16
References m_sleep_time, m_threads, and m_threads_mutex.
Referenced by MTL::MTLThreadPool::MTLThreadPool().
~MTLThreadManager()
MTL::MTLThreadManager::~MTLThreadManager () virtual
Destroy the MTLThreadManager object.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
addThread()
void MTL::MTLThreadManager::addThread (std::unique_ptr< MTLThread > thread)
Add a thread to the thread manager.
Parameters
thread the thread to add.
Author
@ZigRazor
Date
2020-02-16
References m_threads, and m_threads_mutex.
Referenced by MTL::MTLThreadPool::MTLThreadPool().
clean_exit()
void MTL::MTLThreadManager::clean_exit () virtual
A clean Exit of the thread manager.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::MTLThread::clean_exit(), MTL::CREATED, MTL::MTLThread::getThreadState(), m_threads, m_threads_mutex, and MTL::MTLThread::run().
force_exit()
void MTL::MTLThreadManager::force_exit () virtual
Force the thread manager to exit.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::MTLThread::force_exit(), m_threads, and m_threads_mutex.
resume()
void MTL::MTLThreadManager::resume () virtual
Resume the thread manager.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
run()
void MTL::MTLThreadManager::run (MTLThreadInterface * threadIf) virtual
Start the thread manager.
Parameters
threadIf the thread interface.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::CREATED, MTL::EXITED, MTL::FORCE_EXITED, MTL::MTLThreadInterface::getThreadState(), MTL::MTLThread::getThreadState(), MTL::MTLThread::isRunning(), MTL::MTLThread::join(), m_sleep_time, m_threads, m_threads_mutex, MTL::MTLThread::run(), MTL::STOPPED, and MTL::SUSPENDED.
setSleepTime()
void MTL::MTLThreadManager::setSleepTime (int sleep_time)
Set the Sleep Time object.
Parameters
sleep_time Sleep time in milliseconds.
Author
@ZigRazor
Date
2020-02-16
References m_sleep_time.
stop()
void MTL::MTLThreadManager::stop () virtual
Stop the thread manager.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
suspend()
void MTL::MTLThreadManager::suspend () virtual
Suspend the thread manager.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
Field Documentation
m_sleep_time
unsigned int MTL::MTLThreadManager::m_sleep_time private
The sleep time.
Referenced by MTLThreadManager(), run(), and setSleepTime().
m_threads
std::vector<std::unique_ptr<MTLThread> > MTL::MTLThreadManager::m_threads protected
The threads vector.
Referenced by addThread(), clean_exit(), force_exit(), MTLThreadManager(), and run().
m_threads_mutex
std::mutex MTL::MTLThreadManager::m_threads_mutex protected
The threads mutex.
Referenced by addThread(), clean_exit(), force_exit(), MTLThreadManager(), and run().
The documentation for this class was generated from the following files:
include/MTLThreadManager.h
src/MTLThreadManager.cpp