MTL: MySharedObject Class Reference
MySharedObject Class Reference
Public Member Functions
MySharedObject (unsigned int id)
~MySharedObject ()
int getValue ()
void setValue (int v)
Public Member Functions inherited from MTL::MTLSharedObject
MTLSharedObject (SharedObjectId id)
Construct a new MTLSharedObject object.
virtual ~MTLSharedObject ()
Destroy the MTLSharedObject object.
SharedObjectId getObjId ()
Get the id of the object.
MTLSharedObject & getObj ()
Lock the object and Get the object reference.
void releaseObj ()
Release the object lock. (this function should be used only after the end of the critical section that use the object)
Private Attributes
int value
Constructor & Destructor Documentation
MySharedObject()
MySharedObject::MySharedObject (unsigned int id) inline
References MTL::MTLSharedObject::MTLSharedObject(), and value.
Referenced by main().
~MySharedObject()
MySharedObject::~MySharedObject () inline
Member Function Documentation
getValue()
int MySharedObject::getValue () inline
References value.
Referenced by MyRunnable::run().
setValue()
void MySharedObject::setValue (int v) inline
References value.
Referenced by MyRunnable::run().
Field Documentation
value
int MySharedObject::value private
Referenced by getValue(), MySharedObject(), and setValue().
The documentation for this class was generated from the following file:
example/example_5/main.cpp