MTL: MyWorker1 Class Reference
MyWorker1 Class Reference
Public Member Functions
MyWorker1 ()=default
virtual ~MyWorker1 ()=default
virtual void processMessage (MTL::Message message) override
Process the message Message.
void clean_exit () override
A clean Exit of the Thread.
MyWorker1 ()=default
virtual ~MyWorker1 ()=default
virtual void processMessage (MTL::Message message) override
Process the message Message.
void clean_exit () override
A clean Exit of the Thread.
Public Member Functions inherited from MTL::MTLWorkerThread
MTLWorkerThread ()
Construct a new MTLWorkerThread object.
virtual ~MTLWorkerThread ()
Destroy the MTLWorkerThread object.
virtual void run (MTLThreadInterface *threadIf)
Start the thread.
virtual void suspend ()
Suspend the thread.
virtual void resume ()
Resume the thread.
virtual void stop ()
Stop the thread.
virtual void force_exit ()
Force the thread to exit.
void setSleepTime (int sleep_time)
Set the Sleep Time.
Public Member Functions inherited from MTL::MTLMessageQueue
MTLMessageQueue ()
Construct a new MTLMessageQueue object.
virtual ~MTLMessageQueue ()
Destroy the MTLMessageQueue object.
virtual void pushMessage (Message message)
Add a message to the queue.
virtual Message popMessage ()
Get the next message from the queue.
virtual bool isEmpty ()
Check if the queue is empty.
virtual void clear ()
Clear the Queue.
virtual unsigned int getQueueSize ()
Get the Queue Size object.
Additional Inherited Members
Constructor & Destructor Documentation
MyWorker1() [1/2]
MyWorker1::MyWorker1 () default
~MyWorker1() [1/2]
virtual MyWorker1::~MyWorker1 () virtual default
MyWorker1() [2/2]
MyWorker1::MyWorker1 () default
~MyWorker1() [2/2]
virtual MyWorker1::~MyWorker1 () virtual default
Member Function Documentation
clean_exit() [1/2]
void MyWorker1::clean_exit () inline override virtual
A clean Exit of the Thread.
Author
@ZigRazor
Date
2020-02-16
Reimplemented from MTL::MTLWorkerThread.
References MTL::MTLWorkerThread::clean_exit(), and MTL::MTLMessageQueue::getQueueSize().
clean_exit() [2/2]
void MyWorker1::clean_exit () inline override virtual
A clean Exit of the Thread.
Author
@ZigRazor
Date
2020-02-16
Reimplemented from MTL::MTLWorkerThread.
References MTL::MTLWorkerThread::clean_exit().
processMessage() [1/2]
virtual void MyWorker1::processMessage (MTL::Message message) inline override virtual
Process the message Message.
Parameters
message The message to process.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLWorkerThread.
processMessage() [2/2]
virtual void MyWorker1::processMessage (MTL::Message message) inline override virtual
Process the message Message.
Parameters
message The message to process.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLWorkerThread.
The documentation for this class was generated from the following file:
example/example_3/main.cpp