MTL: MTL::MTLSharedMemory Class Reference
MTL::MTLSharedMemory Class Reference
Class that implements a shared memory.
#include <MTLSharedMemory.h>
Public Member Functions
MTLSharedMemory ()
Construct a new MTLSharedMemory object.
virtual ~MTLSharedMemory ()
Destroy the MTLSharedMemory object.
void addSharedObject (std::unique_ptr< MTLSharedObject > obj)
Add a shared object to the shared memory.
void removeSharedObject (SharedObjectId id)
Remove a shared object from the shared memory.
MTLSharedObject & getSharedObjectById (SharedObjectId id)
Get a shared object from the shared memory.
void releaseSharedObject (MTLSharedObject &obj)
Release a shared object from the shared memory.
void clearSharedMemory ()
Clear the shared memory.
Private Attributes
std::map< SharedObjectId, std::unique_ptr< MTLSharedObject > > m_sharedObjects
The shared objects.
Detailed Description
Class that implements a shared memory.
This class is a shared memory that can be used to share data between threads.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLSharedMemory()
MTL::MTLSharedMemory::MTLSharedMemory ()
Construct a new MTLSharedMemory object.
Author
@ZigRazor
Date
2020-02-16
References m_sharedObjects.
~MTLSharedMemory()
MTL::MTLSharedMemory::~MTLSharedMemory () virtual
Destroy the MTLSharedMemory object.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
addSharedObject()
void MTL::MTLSharedMemory::addSharedObject (std::unique_ptr< MTLSharedObject > obj)
Add a shared object to the shared memory.
Parameters
obj The shared object to add.
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLSharedObject::getObjId(), and m_sharedObjects.
clearSharedMemory()
void MTL::MTLSharedMemory::clearSharedMemory ()
Clear the shared memory.
Author
@ZigRazor
Date
2020-02-16
References m_sharedObjects.
getSharedObjectById()
MTLSharedObject & MTL::MTLSharedMemory::getSharedObjectById (SharedObjectId id)
Get a shared object from the shared memory.
Parameters
id The id of the shared object to get.
Returns
MTLSharedObject& The shared object.
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLSharedObject::getObj(), and m_sharedObjects.
releaseSharedObject()
void MTL::MTLSharedMemory::releaseSharedObject (MTLSharedObject & obj)
Release a shared object from the shared memory.
Parameters
obj The shared object to release.
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLSharedObject::getObjId(), m_sharedObjects, and MTL::MTLSharedObject::releaseObj().
removeSharedObject()
void MTL::MTLSharedMemory::removeSharedObject (SharedObjectId id)
Remove a shared object from the shared memory.
Parameters
id The id of the shared object to remove.
Author
@ZigRazor
Date
2020-02-16
References m_sharedObjects.
Field Documentation
m_sharedObjects
std::map<SharedObjectId, std::unique_ptr<MTLSharedObject> > MTL::MTLSharedMemory::m_sharedObjects private
The shared objects.
Referenced by addSharedObject(), clearSharedMemory(), getSharedObjectById(), MTLSharedMemory(), releaseSharedObject(), and removeSharedObject().
The documentation for this class was generated from the following files:
include/MTLSharedMemory.h
src/MTLSharedMemory.cpp