MTL: MTL::MTLWorkerThread Class Reference
MTL::MTLWorkerThread Class Reference abstract
Class that implements a Worker Thread.
#include <MTLWorkerThread.h>
Public Member Functions
MTLWorkerThread ()
Construct a new MTLWorkerThread object.
virtual ~MTLWorkerThread ()
Destroy the MTLWorkerThread object.
virtual void run (MTLThreadInterface *threadIf)
Start the thread.
virtual void suspend ()
Suspend the thread.
virtual void resume ()
Resume the thread.
virtual void stop ()
Stop the thread.
virtual void clean_exit ()
A clean Exit of the Thread.
virtual void force_exit ()
Force the thread to exit.
void setSleepTime (int sleep_time)
Set the Sleep Time.
Public Member Functions inherited from MTL::MTLMessageQueue
MTLMessageQueue ()
Construct a new MTLMessageQueue object.
virtual ~MTLMessageQueue ()
Destroy the MTLMessageQueue object.
virtual void pushMessage (Message message)
Add a message to the queue.
virtual Message popMessage ()
Get the next message from the queue.
virtual bool isEmpty ()
Check if the queue is empty.
virtual void clear ()
Clear the Queue.
virtual unsigned int getQueueSize ()
Get the Queue Size object.
Protected Member Functions
virtual void processMessage (Message message)=0
Process the message Message.
Private Attributes
unsigned int m_sleep_time
Detailed Description
Class that implements a Worker Thread.
This class is a Worker Thread that can be used to run a task.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLWorkerThread()
MTL::MTLWorkerThread::MTLWorkerThread ()
Construct a new MTLWorkerThread object.
Author
@ZigRazor
Date
2020-02-16
References m_sleep_time, and MTL::MTLMessageQueue::MTLMessageQueue().
~MTLWorkerThread()
MTL::MTLWorkerThread::~MTLWorkerThread () virtual
Destroy the MTLWorkerThread object.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
clean_exit()
void MTL::MTLWorkerThread::clean_exit () virtual
A clean Exit of the Thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
force_exit()
void MTL::MTLWorkerThread::force_exit () virtual
Force the thread to exit.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
processMessage()
virtual void MTL::MTLWorkerThread::processMessage (Message message) protected pure virtual
Process the message Message.
Parameters
message The message to process.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLWorker.
Referenced by run().
resume()
void MTL::MTLWorkerThread::resume () virtual
Resume the thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
run()
void MTL::MTLWorkerThread::run (MTLThreadInterface * threadIf) virtual
Start the thread.
Parameters
threadIf The thread interface.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::EXITED, MTL::FORCE_EXITED, MTL::MTLThreadInterface::getThreadState(), MTL::MTLMessageQueue::isEmpty(), m_sleep_time, MTL::MTLMessageQueue::popMessage(), processMessage(), MTL::STOPPED, and MTL::SUSPENDED.
setSleepTime()
void MTL::MTLWorkerThread::setSleepTime (int sleep_time)
Set the Sleep Time.
Parameters
sleep_time sleep time in milliseconds.
Author
@ZigRazor
Date
2020-02-16
References m_sleep_time.
stop()
void MTL::MTLWorkerThread::stop () virtual
Stop the thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
suspend()
void MTL::MTLWorkerThread::suspend () virtual
Suspend the thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
Field Documentation
m_sleep_time
unsigned int MTL::MTLWorkerThread::m_sleep_time private
Sleep time in milliseconds.
Referenced by MTLWorkerThread(), run(), and setSleepTime().
The documentation for this class was generated from the following files:
include/MTLWorkerThread.h
src/MTLWorkerThread.cpp