.TH "example/example_7/CMakeLists.txt" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example/example_7/CMakeLists.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBproject\fP (example_7) cmake_minimum_required(VERSION 3\&.9) add_executable($"
.br
.ti -1c
.RI "\fBmain\fP cpp \fBtarget_include_directories\fP (${PROJECT_NAME} PUBLIC '${PROJECT_SOURCE_DIR}/include') target_link_libraries($"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "project (example_7)"

.SS "\fBmain\fP cpp target_include_directories ( ${PROJECT_NAME} PUBLIC '${PROJECT_SOURCE_DIR}/include')"

.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
