.TH "example/example_7/main.cpp" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example/example_7/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'MTL\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBVar2Task\fP"
.br
.ti -1c
.RI "class \fBSumTask\fP"
.br
.ti -1c
.RI "class \fBMulTask\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
References MTL::MTLTaskFlow::getResult(), MTL::MTLTaskFlow::precede(), and MTL::MTLTaskFlow::run()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
