.TH "include/MTLMessageQueue.h" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MTLMessageQueue.h
.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <queue>\fP
.br
\fC#include 'MTLTypedefs\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMTL::MTLMessageQueue\fP"
.br
.RI "Class that implements a message queue\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMTL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
