.TH "include/MTLSharedMemory.h" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MTLSharedMemory.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MTLSharedObject\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMTL::MTLSharedMemory\fP"
.br
.RI "Class that implements a shared memory\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMTL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
