.TH "include/MTLTask.h" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MTLTask.h
.SH SYNOPSIS
.br
.PP
\fC#include <future>\fP
.br
\fC#include 'MTLTaskInterface\&.h'\fP
.br
\fC#include 'MTLRunnableTask\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMTL::MTLTask\fP"
.br
.RI "The Class that represent a task\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMTL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
