.TH "include/MTLThread.h" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MTLThread.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MTLRunnable\&.h'\fP
.br
\fC#include 'MTLThreadInterface\&.h'\fP
.br
\fC#include <thread>\fP
.br
\fC#include <mutex>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMTL::MTLThread\fP"
.br
.RI "Class that implements a thread\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMTL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
