.TH "include/MTLTaskInterface.h" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MTLTaskInterface.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMTL::MTLTaskInterface\fP"
.br
.RI "The \fBMTLTaskInterface\fP Interface Class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMTL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
