.TH "MyWorker3" 3 "Fri Feb 25 2022" "Version 0.0.1" "MTL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyWorker3
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMTL::MTLWorkerThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyWorker3\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~MyWorker3\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBprocessMessage\fP (\fBMTL::Message\fP message) override"
.br
.RI "Process the message Message\&. "
.ti -1c
.RI "void \fBclean_exit\fP () override"
.br
.RI "A clean Exit of the Thread\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyWorker3::MyWorker3 ()\fC [default]\fP"

.SS "virtual MyWorker3::~MyWorker3 ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void MyWorker3::clean_exit ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
A clean Exit of the Thread\&. 
.PP
\fBAuthor\fP
.RS 4
@ZigRazor 
.RE
.PP
\fBDate\fP
.RS 4
2020-02-16 
.RE
.PP

.PP
Reimplemented from \fBMTL::MTLWorkerThread\fP\&.
.PP
References MTL::MTLWorkerThread::clean_exit(), and MTL::MTLMessageQueue::getQueueSize()\&.
.SS "virtual void MyWorker3::processMessage (\fBMTL::Message\fP message)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Process the message Message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP The message to process\&.
.RE
.PP
\fBAuthor\fP
.RS 4
@ZigRazor 
.RE
.PP
\fBDate\fP
.RS 4
2020-02-16 
.RE
.PP

.PP
Implements \fBMTL::MTLWorkerThread\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTL from the source code\&.
