MTL: MTL::MTLThreadPool Class Reference
MTL::MTLThreadPool Class Reference
Class that implements a thread pool.
#include <MTLThreadPool.h>
Public Member Functions
MTLThreadPool (MTLWorkerThread &worker, unsigned int num_threads)
Construct a new MTLThreadPool object.
~MTLThreadPool ()
Destroy the MTLThreadPool object.
virtual void onMessage (Message &message)
Dispatch a message to the thread pool.
Public Member Functions inherited from MTL::MTLThreadManager
MTLThreadManager ()
Construct a new MTLThreadManager object.
virtual ~MTLThreadManager ()
Destroy the MTLThreadManager object.
virtual void run (MTLThreadInterface *threadIf)
Start the thread manager.
virtual void suspend ()
Suspend the thread manager.
virtual void resume ()
Resume the thread manager.
virtual void stop ()
Stop the thread manager.
virtual void clean_exit ()
A clean Exit of the thread manager.
virtual void force_exit ()
Force the thread manager to exit.
void addThread (std::unique_ptr< MTLThread > thread)
Add a thread to the thread manager.
void setSleepTime (int sleep_time)
Set the Sleep Time object.
Private Attributes
std::mutex m_onMessage_mutex
unsigned int m_num_threads
unsigned int m_current_thread
MTLWorkerThread & worker
Additional Inherited Members
Protected Attributes inherited from MTL::MTLThreadManager
std::vector< std::unique_ptr< MTLThread > > m_threads
std::mutex m_threads_mutex
Detailed Description
Class that implements a thread pool.
This class is a thread pool that can be used to manage threads.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLThreadPool()
MTL::MTLThreadPool::MTLThreadPool (MTLWorkerThread & worker, unsigned int num_threads)
Construct a new MTLThreadPool object.
Parameters
worker worker thread for the thread pool.
num_threads number of threads in the thread pool.
Author
@ZigRazor
Date
2020-02-16
References MTL::MTLThreadManager::addThread(), m_current_thread, m_num_threads, m_onMessage_mutex, MTL::MTLThread::MTLThread(), MTL::MTLThreadManager::MTLThreadManager(), and worker.
~MTLThreadPool()
MTL::MTLThreadPool::~MTLThreadPool ()
Destroy the MTLThreadPool object.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
onMessage()
void MTL::MTLThreadPool::onMessage (Message & message) virtual
Dispatch a message to the thread pool.
Parameters
message Message to dispatch.
Author
@ZigRazor
Date
2020-02-16
References m_onMessage_mutex, MTL::MTLMessageQueue::pushMessage(), and worker.
Field Documentation
m_current_thread
unsigned int MTL::MTLThreadPool::m_current_thread private
Current thread in the thread pool.
Referenced by MTLThreadPool().
m_num_threads
unsigned int MTL::MTLThreadPool::m_num_threads private
Number of threads in the thread pool.
Referenced by MTLThreadPool().
m_onMessage_mutex
std::mutex MTL::MTLThreadPool::m_onMessage_mutex private
Mutex for the onMessage method.
Referenced by MTLThreadPool(), and onMessage().
worker
MTLWorkerThread& MTL::MTLThreadPool::worker private
Worker thread for the thread pool.
Referenced by MTLThreadPool(), and onMessage().
The documentation for this class was generated from the following files:
include/MTLThreadPool.h
src/MTLThreadPool.cpp