MTL: MTL::MTLThread Class Reference
MTL::MTLThread Class Reference
Class that implements a thread.
#include <MTLThread.h>
Public Member Functions
MTLThread (MTLRunnable &runnable)
Construct a new MTLThread object.
virtual ~MTLThread ()
Destroy the MTLThread object.
virtual void run (MTLThreadInterface *threadIf=nullptr)
Start the thread.
virtual void suspend ()
Suspend the thread.
virtual void resume ()
Resume the thread.
virtual void stop ()
Stop the thread.
virtual void clean_exit ()
A clean Exit of the Thread.
virtual void force_exit ()
Force the thread to exit.
bool isRunning ()
Check if the thread is running.
void join ()
Join the thread.
MTLRunnable & getRunnableReference ()
Get the Runnable Reference object.
E_MTLThreadState getThreadState ()
Get the Thread State.
void setThreadState (E_MTLThreadState threadState)
Set the Thread State object.
Private Attributes
E_MTLThreadState m_threadState
The thread state.
std::mutex m_threadState_mutex
The mutex for the thread state.
std::unique_ptr< std::thread > m_thread_ptr
The thread pointer.
MTLRunnable & m_runnable
The runnable object.
Detailed Description
Class that implements a thread.
This class is a thread that can be used to run a task.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLThread()
MTL::MTLThread::MTLThread (MTLRunnable & runnable)
Construct a new MTLThread object.
Parameters
runnable the runnable object to run.
Author
@ZigRazor
Date
2020-02-16
References MTL::CREATED, m_runnable, m_thread_ptr, m_threadState, and m_threadState_mutex.
Referenced by MTL::MTLThreadPool::MTLThreadPool().
~MTLThread()
MTL::MTLThread::~MTLThread () virtual
Destroy the MTLThread object.
Author
@ZigRazor
Date
2020-02-16
References MTL::EXITED, join(), m_threadState, and m_threadState_mutex.
Member Function Documentation
clean_exit()
void MTL::MTLThread::clean_exit () virtual
A clean Exit of the Thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::MTLRunnable::clean_exit(), MTL::EXITED, m_runnable, m_threadState, and m_threadState_mutex.
Referenced by MTL::MTLThreadManager::clean_exit().
force_exit()
void MTL::MTLThread::force_exit () virtual
Force the thread to exit.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References MTL::MTLRunnable::force_exit(), MTL::FORCE_EXITED, m_runnable, m_threadState, and m_threadState_mutex.
Referenced by MTL::MTLThreadManager::force_exit().
getRunnableReference()
MTLRunnable & MTL::MTLThread::getRunnableReference ()
Get the Runnable Reference object.
Returns
Runnable& get the Runnable Reference object
Author
@ZigRazor
Date
2020-02-16
References m_runnable.
getThreadState()
E_MTLThreadState MTL::MTLThread::getThreadState () virtual
Get the Thread State.
Returns
E_MTLThreadState Thread State
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLThreadInterface.
References m_threadState, and m_threadState_mutex.
Referenced by MTL::MTLThreadManager::clean_exit(), and MTL::MTLThreadManager::run().
isRunning()
bool MTL::MTLThread::isRunning () virtual
Check if the thread is running.
Returns
true if the thread is running.
false if the thread is not running.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLThreadInterface.
References m_threadState, m_threadState_mutex, MTL::RUNNING, MTL::STOPPED, and MTL::SUSPENDED.
Referenced by resume(), MTL::MTLThreadManager::run(), run(), stop(), and suspend().
join()
void MTL::MTLThread::join ()
Join the thread.
Author
@ZigRazor
Date
2020-02-16
References m_thread_ptr.
Referenced by MTL::MTLThreadManager::run(), and ~MTLThread().
resume()
void MTL::MTLThread::resume () virtual
Resume the thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References isRunning(), m_runnable, m_threadState, m_threadState_mutex, MTL::MTLRunnable::resume(), and MTL::RUNNING.
run()
void MTL::MTLThread::run (MTLThreadInterface * threadIf = nullptr) virtual
Start the thread.
Parameters
threadIf The thread interface.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References isRunning(), m_runnable, m_thread_ptr, m_threadState, m_threadState_mutex, MTL::MTLRunnable::run(), and MTL::RUNNING.
Referenced by MTL::MTLThreadManager::clean_exit(), and MTL::MTLThreadManager::run().
setThreadState()
void MTL::MTLThread::setThreadState (E_MTLThreadState threadState) virtual
Set the Thread State object.
Parameters
threadState the Thread State to set
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLThreadInterface.
References m_threadState, and m_threadState_mutex.
stop()
void MTL::MTLThread::stop () virtual
Stop the thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References isRunning(), m_runnable, m_threadState, m_threadState_mutex, MTL::MTLRunnable::stop(), and MTL::STOPPED.
suspend()
void MTL::MTLThread::suspend () virtual
Suspend the thread.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnable.
References isRunning(), m_runnable, m_threadState, m_threadState_mutex, MTL::MTLRunnable::suspend(), and MTL::SUSPENDED.
Field Documentation
m_runnable
MTLRunnable& MTL::MTLThread::m_runnable private
The runnable object.
Referenced by clean_exit(), force_exit(), getRunnableReference(), MTLThread(), resume(), run(), stop(), and suspend().
m_thread_ptr
std::unique_ptr<std::thread> MTL::MTLThread::m_thread_ptr private
The thread pointer.
Referenced by join(), MTLThread(), and run().
m_threadState
E_MTLThreadState MTL::MTLThread::m_threadState private
The thread state.
Referenced by clean_exit(), force_exit(), getThreadState(), isRunning(), MTLThread(), resume(), run(), setThreadState(), stop(), suspend(), and ~MTLThread().
m_threadState_mutex
std::mutex MTL::MTLThread::m_threadState_mutex private
The mutex for the thread state.
Referenced by clean_exit(), force_exit(), getThreadState(), isRunning(), MTLThread(), resume(), run(), setThreadState(), stop(), suspend(), and ~MTLThread().
The documentation for this class was generated from the following files:
include/MTLThread.h
src/MTLThread.cpp