MTL: MTL::MTLRunnable Class Reference
MTL::MTLRunnable Class Reference abstract
Runnable Interface.
#include <MTLRunnable.h>
Public Member Functions
virtual void run (MTLThreadInterface *threadIf)=0
Run the runnable.
virtual void suspend ()=0
Suspend the runnable.
virtual void resume ()=0
Resume the runnable.
virtual void stop ()=0
Stop the runnable.
virtual void clean_exit ()=0
A clean Exit of the runnable.
virtual void force_exit ()=0
Force the runnable to exit.
Private Attributes
MTLThreadInterface * threadIf
The thread interface.
Detailed Description
Runnable Interface.
This class is the interface for the Runnable class.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
clean_exit()
virtual void MTL::MTLRunnable::clean_exit () pure virtual
A clean Exit of the runnable.
Author
@ZigRazor
Date
2020-02-16
Implemented in MTL::MTLThread, MTL::MTLThreadManager, and MTL::MTLWorkerThread.
Referenced by MTL::MTLThread::clean_exit().
force_exit()
virtual void MTL::MTLRunnable::force_exit () pure virtual
Force the runnable to exit.
Author
@ZigRazor
Date
2020-02-16
Implemented in MTL::MTLThread, MTL::MTLThreadManager, and MTL::MTLWorkerThread.
Referenced by MTL::MTLThread::force_exit().
resume()
virtual void MTL::MTLRunnable::resume () pure virtual
Resume the runnable.
Author
@ZigRazor
Date
2020-02-16
Implemented in MTL::MTLThread, MTL::MTLThreadManager, and MTL::MTLWorkerThread.
Referenced by MTL::MTLThread::resume().
run()
virtual void MTL::MTLRunnable::run (MTLThreadInterface * threadIf) pure virtual
Run the runnable.
Parameters
threadIf The thread interface.
Author
@ZigRazor
Date
2020-02-16
Implemented in MTL::MTLThread, MTL::MTLThreadManager, and MTL::MTLWorkerThread.
Referenced by MTL::MTLThread::run().
stop()
virtual void MTL::MTLRunnable::stop () pure virtual
Stop the runnable.
Author
@ZigRazor
Date
2020-02-16
Implemented in MTL::MTLThread, MTL::MTLThreadManager, and MTL::MTLWorkerThread.
Referenced by MTL::MTLThread::stop().
suspend()
virtual void MTL::MTLRunnable::suspend () pure virtual
Suspend the runnable.
Author
@ZigRazor
Date
2020-02-16
Implemented in MTL::MTLThread, MTL::MTLThreadManager, and MTL::MTLWorkerThread.
Referenced by MTL::MTLThread::suspend().
Field Documentation
threadIf
MTLThreadInterface* MTL::MTLRunnable::threadIf private
The thread interface.
The documentation for this class was generated from the following file:
include/MTLRunnable.h