MTL: MTL::MTLTask Class Reference
MTL::MTLTask Class Reference
The Class that represent a task.
#include <MTLTask.h>
Public Member Functions
MTLTask (MTLRunnableTask &runnableTask)
Construct a new MTLTask object.
virtual ~MTLTask ()
Destroy the MTLTask object.
virtual std::shared_ptr< void > run (MTLTaskInterface *interface=nullptr)
Execute the task.
virtual std::shared_ptr< void > getResult ()
Get the result of the task. When the execution is finished and the result is available.
virtual void waitResult ()
Wait for the result of the task.
Protected Attributes
MTLRunnableTask & m_runnableTask
The runnable task.
std::future< std::shared_ptr< void > > m_future
The future object.
std::mutex m_futureMutex
The mutex for the future object.
std::shared_ptr< void > m_result
The result of the task.
Detailed Description
The Class that represent a task.
This class is the base class for all the task.
Author
@ZigRazor
Date
2020-02-16
Constructor & Destructor Documentation
MTLTask()
MTL::MTLTask::MTLTask (MTLRunnableTask & runnableTask)
Construct a new MTLTask object.
Parameters
runnableTask The runnable task.
Author
@ZigRazor
Date
2020-02-16
References m_future, m_futureMutex, m_result, and m_runnableTask.
Referenced by MTL::MTLOrderedTask::MTLOrderedTask().
~MTLTask()
MTL::MTLTask::~MTLTask () virtual
Destroy the MTLTask object.
Author
@ZigRazor
Date
2020-02-16
Member Function Documentation
getResult()
std::shared_ptr< void > MTL::MTLTask::getResult () virtual
Get the result of the task. When the execution is finished and the result is available.
Returns
std::shared_ptr<void> The result of the task
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLTaskInterface.
Reimplemented in MTL::MTLTaskFlow.
References m_future, m_futureMutex, and m_result.
Referenced by MTL::MTLOrderedTask::getPredecessorResult(), MTL::MTLOrderedTask::getPredecessorsResults(), and MTL::MTLTaskFlow::getResult().
run()
std::shared_ptr< void > MTL::MTLTask::run (MTLTaskInterface * interface = nullptr) virtual
Execute the task.
Returns
std::shared_ptr<void> The result of the run.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLRunnableTask.
Reimplemented in MTL::MTLOrderedTask, and MTL::MTLTaskFlow.
References m_future, m_runnableTask, and MTL::MTLRunnableTask::run().
waitResult()
void MTL::MTLTask::waitResult () virtual
Wait for the result of the task.
Author
@ZigRazor
Date
2020-02-16
Implements MTL::MTLTaskInterface.
Reimplemented in MTL::MTLTaskFlow.
References m_future.
Referenced by MTL::MTLTaskFlow::waitResult().
Field Documentation
m_future
std::future<std::shared_ptr<void> > MTL::MTLTask::m_future protected
The future object.
Referenced by getResult(), MTLTask(), run(), MTL::MTLOrderedTask::run(), and waitResult().
m_futureMutex
std::mutex MTL::MTLTask::m_futureMutex protected
The mutex for the future object.
Referenced by getResult(), and MTLTask().
m_result
std::shared_ptr<void> MTL::MTLTask::m_result protected
The result of the task.
Referenced by getResult(), and MTLTask().
m_runnableTask
MTLRunnableTask& MTL::MTLTask::m_runnableTask protected
The runnable task.
Referenced by MTLTask(), run(), and MTL::MTLOrderedTask::run().
The documentation for this class was generated from the following files:
include/MTLTask.h
src/MTLTask.cpp